/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useAnimations, useGLTF } from '@react-three/drei';
import React, { useEffect, useRef } from 'react';

export default function Eye({ ready }, props) {
  const group = useRef();
  const { nodes, animations } = useGLTF('/model/MOOD/models/flippers.glb');
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    // You can play, stop, fade actions in here
    if (ready) {
      actions.eyesAction.play();
    }
  }, [actions, ready]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="eyesEmpty" position={[0, 1.27, 0]}>
          <mesh
            name="leftEye"
            castShadow
            receiveShadow
            geometry={nodes.leftEye.geometry}
            material={nodes.leftEye.material}
            position={[0, 0, 0.26]}
          />
          <mesh
            name="rightEye"
            castShadow
            receiveShadow
            geometry={nodes.rightEye.geometry}
            material={nodes.rightEye.material}
            position={[0, 0, -0.26]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/model/MOOD/models/flippers.glb');
