/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useAnimations, useGLTF } from '@react-three/drei';
import React, { useEffect, useRef } from 'react';

export default function Hat({ ready, currentMesh, set, material }, props) {
  const group = useRef();
  const { nodes, animations } = useGLTF('/model/MOOD/models/flippers.glb');
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (ready) {
      actions.hatAction.play();
    }
  }, [actions, ready]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="hatEmpty" position={[0, 1.52, 0]}>
          <mesh
            visible={currentMesh === 0}
            name="hat_1"
            castShadow
            receiveShadow
            geometry={nodes.hat_1.geometry}
            material={material}
            position={[0, -1.52, 0]}
          />
          <mesh
            visible={currentMesh === 1}
            name="hat_2"
            castShadow
            receiveShadow
            geometry={nodes.hat_2.geometry}
            material={material}
            position={[0, -1.52, 0]}
          />
          <mesh
            visible={currentMesh === 2}
            name="hat_3"
            castShadow
            receiveShadow
            geometry={nodes.hat_3.geometry}
            material={material}
            position={[0, -1.52, 0]}
          />
          <mesh
            visible={currentMesh === 3}
            name="hat_4"
            castShadow
            receiveShadow
            geometry={nodes.hat_4.geometry}
            material={material}
            position={[0, -1.52, 0]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/model/MOOD/models/flippers.glb');
