/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useAnimations, useGLTF } from '@react-three/drei';
import React, { useEffect, useRef } from 'react';

export default function Hat({ ready, currentMesh, set }, props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/model/MOOD/models/flippers.glb');
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (ready) {
      actions.hatAction.play();
    }
  }, [actions, ready]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="hatEmpty" position={[0, 1.52, 0]}>
          <mesh
            visible={currentMesh === 0}
            name="hat_1"
            castShadow
            receiveShadow
            geometry={nodes.hat_1.geometry}
            material={nodes.hat_1.material}
            position={[0, 0.29, 0]}
            scale={0.84}
          />
          <mesh
            visible={currentMesh === 1}
            name="hat_2"
            castShadow
            receiveShadow
            geometry={nodes.hat_2.geometry}
            material={nodes.hat_2.material}
            position={[-0.1, 0, 0]}
            rotation={[0, 0, 0.1]}
            scale={[0.43, 0.43, 0.43]}
          />
          <mesh
            visible={currentMesh === 2}
            name="hat_3"
            castShadow
            receiveShadow
            geometry={nodes.hat_3.geometry}
            material={nodes.hat_3.material}
            position={[0, 0.05, 0]}
            scale={0.36}
          />
          <mesh
            visible={currentMesh === 3}
            name="hat_4"
            castShadow
            receiveShadow
            geometry={nodes.hat_4.geometry}
            material={nodes.hat_4.material}
            position={[0, -0.08, 0]}
            scale={0.6}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/model/MOOD/models/flippers.glb');
