/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useAnimations, useGLTF } from '@react-three/drei';
import React, { useEffect, useRef } from 'react';

export default function Mouth({ ready }, props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/model/MOOD/models/flippers.glb');
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    // You can play, stop, fade actions in here
    if (ready) {
      actions.mouthAction.play();
    }
  }, [actions, ready]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="mouthEmpty">
          <group name="mouth">
            <mesh
              name="Cube001"
              castShadow
              receiveShadow
              geometry={nodes.Cube001.geometry}
              material={materials.yellow}
            />
            <mesh
              name="Cube001_1"
              castShadow
              receiveShadow
              geometry={nodes.Cube001_1.geometry}
              material={nodes.Cube001_1.material}
            />
            <mesh
              name="Cube001_2"
              castShadow
              receiveShadow
              geometry={nodes.Cube001_2.geometry}
              material={nodes.Cube001_2.material}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/model/MOOD/models/flippers.glb');
