/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useAnimations, useGLTF } from '@react-three/drei';
import React, { useEffect, useRef } from 'react';

export default function Mouth({ ready, currentMesh, set, material }, props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/model/MOOD/models/flippers.glb');
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (ready) {
      actions.mouthAction.play();
    }
  }, [actions, ready]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Mouth Scene">
        <group name="mouthEmpty">
          <group name="mouth_1" visible={currentMesh === 0}>
            <mesh
              name="Cube009"
              castShadow
              receiveShadow
              geometry={nodes.Cube009.geometry}
              material={nodes.Cube009.material}
            />
            <mesh
              name="Cube009_1"
              castShadow
              receiveShadow
              geometry={nodes.Cube009_1.geometry}
              material={nodes.Cube009_1.material}
            />
            <mesh
              name="Cube009_2"
              castShadow
              receiveShadow
              geometry={nodes.Cube009_2.geometry}
              material={nodes.Cube009_2.material}
            />
          </group>
          <group name="mouth_2" position={[0, 0.01, 0]} rotation={[0, 0, 3.14]} visible={currentMesh === 1}>
            <mesh
              name="Cylinder019"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder019.geometry}
              material={nodes.Cylinder019.material}
            />
            <mesh
              name="Cylinder019_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder019_1.geometry}
              material={nodes.Cylinder019_1.material}
            />
          </group>
          <group name="mouth_3" visible={currentMesh === 2}>
            <mesh
              name="Cube013"
              castShadow
              receiveShadow
              geometry={nodes.Cube013.geometry}
              material={nodes.Cube013.material}
            />
            <mesh
              name="Cube013_1"
              castShadow
              receiveShadow
              geometry={nodes.Cube013_1.geometry}
              material={nodes.Cube013_1.material}
            />
          </group>
          <group name="mouth_4" position={[0, 0.03, 0]} visible={currentMesh === 3}>
            <mesh
              name="Cube018"
              castShadow
              receiveShadow
              geometry={nodes.Cube018.geometry}
              material={nodes.Cube018.material}
            />
            <mesh
              name="Cube018_1"
              castShadow
              receiveShadow
              geometry={nodes.Cube018_1.geometry}
              material={nodes.Cube018_1.material}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/model/MOOD/models/flippers.glb');
