/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useAnimations, useGLTF } from '@react-three/drei';
import React, { useEffect, useRef } from 'react';

export default function Neck({ ready }, props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/model/MOOD/models/flippers.glb');
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    // You can play, stop, fade actions in here
    if (ready) {
      actions.neckAction.play();
    }
  }, [actions, ready]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="neck"
          castShadow
          receiveShadow
          geometry={nodes.neck.geometry}
          material={materials.green}
          position={[0, 0.04, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/model/MOOD/models/flippers.glb');
