/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useAnimations, useGLTF } from '@react-three/drei';
import React, { useEffect, useRef, useState } from 'react';

import { onChangeMesh } from '../hooks/onChangeMesh';

export default function Neck({ ready, currentMesh, set }, props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/model/MOOD/models/flippers.glb');
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (ready) {
      actions.neckAction.play();
    }
  }, [actions, ready]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Neck Scene" onClick={() => onChangeMesh(currentMesh, set)}>
        <group name="neckEmpty" position={[0, -1.33, 0]}>
          <mesh
            visible={currentMesh === 0}
            name="neck_1"
            castShadow
            receiveShadow
            geometry={nodes.neck_1.geometry}
            material={nodes.neck_1.material}
            position={[0, 1.37, 0]}
          />
          <mesh
            visible={currentMesh === 1}
            name="neck_2"
            castShadow
            receiveShadow
            geometry={nodes.neck_2.geometry}
            material={nodes.neck_2.material}
            position={[0, -0.28, 0]}
          />
          <mesh
            visible={currentMesh === 2}
            name="neck_3"
            castShadow
            receiveShadow
            geometry={nodes.neck_3.geometry}
            material={nodes.neck_3.material}
            position={[0, -0.23, 0]}
            scale={0.37}
          />
          <mesh
            visible={currentMesh === 3}
            name="neck_4"
            castShadow
            receiveShadow
            geometry={nodes.neck_4.geometry}
            material={materials.orange}
            position={[0, 1.31, 0]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/model/MOOD/models/flippers.glb');
