/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { config, useSpring } from '@react-spring/three';
import { useGLTF, useMatcapTexture } from '@react-three/drei';
import React, { useRef } from 'react';

export default function InterfacesLogo(props) {
  const group = useRef();
  const { nodes } = useGLTF('/model/interfaces_logo.glb');
  const [matcap] = useMatcapTexture('8194AB_D6DFEB_C0CEDE_B0BFD1', 1024);

  const { position } = useSpring({
    position: [0, 0, 0],
    config: config.gentle,
  });
  const { rotation } = useSpring({
    rotation: Math.PI,
    loop: true,
  });
  return (
    <group ref={group} {...props} dispose={null} position={[0, 0, 0]} rotation={rotation}>
      <mesh castShadow receiveShadow geometry={nodes.path1.geometry} material={nodes.path1.material}>
        <meshMatcapMaterial matcap={matcap} />
      </mesh>
    </group>
  );
}

useGLTF.preload('/interfaces_logo.glb');
