/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { a, easings, useSpring } from '@react-spring/three';
import { useGLTF } from '@react-three/drei';
import React, { useEffect, useRef } from 'react';

export default function Model({ floatDuration }, props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/model/MOOD/models/flippers.glb');

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Cube001.geometry} material={materials.green} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={nodes.Cylinder.material}
        position={[0, -0.42, 0]}
      >
        <mesh castShadow receiveShadow geometry={nodes.Cylinder001.geometry} material={nodes.Cylinder001.material} />
      </mesh>
      <mesh castShadow receiveShadow geometry={nodes.Cube001_1.geometry} material={materials.yellow} />
      <mesh castShadow receiveShadow geometry={nodes.Cube001_2.geometry} material={materials.moutth} />
    </group>
  );
}

useGLTF.preload('/model/MOOD/models/flippers.glb');
